package com.geinimi;

enum p {
    ACTION_START_OK,
    ACTION_IDLE_TO_DOWNLOAD,
    ACTION_DOWNLOAD_OK,
    ACTION_DOWNLOAD_FAILUE,
    ACTION_PARSE_OK,
    ACTION_PARSE_FAILUE,
    ACTION_TRANSACT_OK,
    ACTION_TRANSACT_FAILUE;

    static {
        ACTION_START_OK = new p("ACTION_START_OK", 0);
        ACTION_IDLE_TO_DOWNLOAD = new p("ACTION_IDLE_TO_DOWNLOAD", 1);
        ACTION_DOWNLOAD_OK = new p("ACTION_DOWNLOAD_OK", 2);
        ACTION_DOWNLOAD_FAILUE = new p("ACTION_DOWNLOAD_FAILUE", 3);
        ACTION_PARSE_OK = new p("ACTION_PARSE_OK", 4);
        ACTION_PARSE_FAILUE = new p("ACTION_PARSE_FAILUE", 5);
        ACTION_TRANSACT_OK = new p("ACTION_TRANSACT_OK", 6);
        ACTION_TRANSACT_FAILUE = new p("ACTION_TRANSACT_FAILUE", 7);
        p[] pVarArr = {ACTION_START_OK, ACTION_IDLE_TO_DOWNLOAD, ACTION_DOWNLOAD_OK, ACTION_DOWNLOAD_FAILUE, ACTION_PARSE_OK, ACTION_PARSE_FAILUE, ACTION_TRANSACT_OK, ACTION_TRANSACT_FAILUE};
    }
}
